[template]
src = "dockerfile.tmpl"
dest = "{{SOURCE_ROOTDIR}}/Dockerfile"
keys = [
    "/meta/confd/version",
    "/meta/consul/version",
    "/meta/cloud/newrelic/licensekey",
    "/meta/node/admin/defaultpasswd",
]