# -----------------------------------------------------------------------------
# Ubuntu-based Configuration Store & Service Discovery Service Image (x64) - Consul
#
# Features:
#   Parametric Design.
#   Support for Legacy/Traditional Remote administration.
#     Administration & Diagnostic Tools.
#   Configuration Management (confd).
#     Boot-time dependency injection.
#   Process Management (supervisor)
#   Cloud-based Monitoring and Application Performance Management (Loggly & NewRelic).
#
#   Configuration Store & Service Discovery Service (Consul)
# -----------------------------------------------------------------------------
# https://github.com/cveira/docker-consul
#   Forked from: https://github.com/progrium/docker-consul
# -----------------------------------------------------------------------------


FROM ubuntu:14.04
# VOLUME /data
MAINTAINER Carlos Veira Lorenzo "cveira@thinkinbig.org"


# -----------------------------------------------------------------------------
# Docker environment

ENV DEBIAN_FRONTEND noninteractive

ENV CONFD_VERSION {{getv "/meta/confd/version"}}
ENV CONSUL_VERSION {{getv "/meta/consul/version"}}

ENV SHELL /bin/bash
ENV PATH ${PATH}:/root/scripts


# -----------------------------------------------------------------------------
# Package deployment

RUN mkdir /root/tmp
WORKDIR /root/tmp

RUN \
  export LANGUAGE=en_US.UTF-8 && \
  export LANG=en_US.UTF-8 && \
  export LC_ALL=en_US.UTF-8 && \
  locale-gen en_US.UTF-8 && \
  dpkg-reconfigure locales

RUN \
  apt-get update && \
  apt-get install -y bash curl lftp wget git htop mc man zip unzip vim nano ltrace strace multitail openssh-server supervisor monit nmap socat dnsutils traceroute gnupg

RUN \
  apt-get update && \
  apt-get install -y build-essential && \
  apt-get install -y python

RUN \
  echo "deb http://apt.newrelic.com/debian/ newrelic non-free" >> /etc/apt/sources.list.d/newrelic.list && \
  wget -O - https://download.newrelic.com/548C16BF.gpg | apt-key add - && \
  apt-get update && \
  apt-get install -y newrelic-sysmond newrelic-daemon

RUN \
  wget -O - https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python && \
  pip install newrelic-plugin-agent && \
  cp /opt/newrelic-plugin-agent/newrelic-plugin-agent.cfg /etc/newrelic/ && \
  cp /opt/newrelic-plugin-agent/newrelic-plugin-agent.deb /etc/init.d/newrelic-plugin-agent && \
  chmod 755 /etc/init.d/newrelic-plugin-agent && \
  mkdir -p /var/run/newrelic

RUN \
  wget -O /root/tmp/confd https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-linux-amd64 && \
  mv /root/tmp/confd /usr/local/bin/confd && \
  chmod +x /usr/local/bin/confd && \
  mkdir -p /etc/confd/conf.d && \
  mkdir -p /etc/confd/templates
COPY settings/confd/ /etc/confd/

ADD https://dl.bintray.com/mitchellh/consul/${CONSUL_VERSION}_linux_amd64.zip /tmp/consul.zip
RUN \
  cd /bin && \
  unzip /tmp/consul.zip && \
  chmod +x /bin/consul && \
  rm -f /tmp/consul.zip

ADD https://dl.bintray.com/mitchellh/consul/${CONSUL_VERSION}_web_ui.zip /tmp/webui.zip
RUN \
  cd /tmp && \
  unzip /tmp/webui.zip && \
  mv dist /ui && \
  rm -f /tmp/webui.zip

RUN apt-get clean -qq


# -----------------------------------------------------------------------------
# System configuration

RUN echo 'root:{{getv "/meta/node/admin/defaultpasswd"}}' | chpasswd

RUN \
  echo "Europe/Amsterdam" > /etc/timezone && \
  dpkg-reconfigure -f noninteractive tzdata

RUN \
  nrsysmond-config --set license_key={{getv "/meta/cloud/newrelic/licensekey"}} && \
  cp /etc/newrelic/newrelic.cfg.template /etc/newrelic/newrelic.cfg && \
  sed -i -e 's/REPLACE_WITH_REAL_KEY/{{getv "/meta/cloud/newrelic/licensekey"}}/g' /etc/newrelic/newrelic-plugin-agent.cfg

RUN \
  mkdir /var/run/sshd && \
  sed -i "s/UsePAM.*/UsePAM yes/g"                   /etc/ssh/sshd_config && \
  sed -i "s/PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config

RUN \
  touch /var/log/syslog /var/log/kern.log /var/log/debug /var/log/mail.log /var/log/mail.err && \
  chown syslog:adm /var/log/syslog /var/log/kern.log /var/log/debug /var/log/mail.log /var/log/mail.err && \
  chmod 640 /var/log/syslog /var/log/kern.log /var/log/debug /var/log/mail.log /var/log/mail.err && \
  sed -i 's/^[#\t\s]*\(\*\.=notice;\*\.=warn\).*xconsole$/\t\1\t\-\/var\/log\/syslog/' /etc/rsyslog.d/50-default.conf

COPY settings/rsyslog-modload.conf           /etc/rsyslog.d/0-rsyslog-modload.conf
COPY settings/loggly-sysauth.conf            /etc/rsyslog.d/5-loggly-sysauth.conf
COPY settings/loggly-monit.conf              /etc/rsyslog.d/8-loggly-monit.conf
COPY settings/loggly-supervisord.conf        /etc/rsyslog.d/9-loggly-supervisord.conf
COPY settings/loggly-newrelic-sysmond.conf   /etc/rsyslog.d/10-loggly-newrelic-sysmond.conf
COPY settings/loggly-newrelic-daemon.conf    /etc/rsyslog.d/11-loggly-newrelic-daemon.conf
COPY settings/loggly-newrelic-pa.conf        /etc/rsyslog.d/12-loggly-newrelic-pa.conf
COPY settings/loggly.conf                    /etc/rsyslog.d/22-loggly.conf

RUN mkdir -p /var/log/supervisor
COPY settings/supervisord-primary.conf   /etc/supervisor/conf.d/
COPY settings/supervisord-secondary.conf /etc/supervisor/conf.d/
COPY settings/monit-system.conf          /etc/monit/conf.d/

RUN mkdir -p /etc/consul/
COPY         ./settings/consul/ /etc/consul/
ONBUILD COPY ./settings/consul/ /etc/consul/


# -----------------------------------------------------------------------------
# Shell environment configuration

COPY settings/.profile             /root/
COPY settings/.profile_preferences /root/
COPY settings/ssh/                 /root/.ssh/
COPY settings/scripts/             /root/scripts/

RUN chmod u+x /root/scripts/*.sh


# -----------------------------------------------------------------------------
# Container execution

WORKDIR /root/scripts/
EXPOSE 22 2812 9001 8300 8301 8301/udp 8302 8302/udp 8400 8500 53/udp

ENTRYPOINT ["/root/scripts/init.sh"]
CMD []